### ISSUE TITLE
Runtime error in Homebridge 1.0.4

### ISSUE THREAD

**Issue by standre** [rxseger/homebridge-camera-motion#18]
The plugin was running properly with homebridge 0.4.53. After the upgrade to 1.0.4 (all other plugins working properly or provide an update) I get:

```
 TypeError: Cannot read property 'length' of undefined
    at Accessory.configureCameraSource (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:541:40)
    at PlatformAccessory.configureCameraSource (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:132:41)
    at CameraMotionPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-camera-motion/camera-motion.js:47:21)
    at HomebridgeAPI.emit (events.js:203:15)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:231:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by morkjt** [comment]
Same issue.

**Comment by zeratax** [comment]
should this issue also be filled against the hap-node? didn't see anything about breaking changes around `configureCameraSource`?

**Comment by cstanger** [comment]
Same issue here as well.

**Comment by Minims** [comment]
Hello, sorry I am not using this anymore. If someone wants to get this project ou make some PR to fix the issue, he is welcome.

**Comment by aftrmth728** [comment]
Me too, did anyone find a workaround or anything?

**Comment by aftrmth728** [comment]
Is anyone using this on an old version of Homebridge successfully? If so, which version are you using? thanks
